---
abstract: 'Bundle for all things needed by Benchmark::Perl::Formance'
author:
  - 'Steffen Schwigon, C<< <ss5@renormalist.net> >>'
build_requires:
  Module::Build: 0.28
  Test::More: 0.17
configure_requires:
  Module::Build: 0.2701
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-PerlFormance
provides:
  Bundle::PerlFormance:
    file: lib/Bundle/PerlFormance.pm
    version: 0.04
recommends:
  Test::Pod: 1.20
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
